const business = [{
  id: 1,
  name: 'x-plug Nig. Ltd',
  services: 'Wed Development',
  phone_number: '09034222567',
  email: 'xplug@gmail.com',
  address: '1, xyz street, Surulere, Lagos',
  category: 'Information Technology',
  location: 'Lagos',
  image: 'url',
  reviews: [{
    id: 1,
    name: 'Tobi Alabi',
    email: 'tobialabi@gmail.com',
    review: 'I love you company and services, just keep it up',
    country: 'USA',
  },
  {
    id: 2,
    name: 'Joseph Tutu',
    email: 'josephtutu@gmail.com',
    review: 'Best Services',
    country: 'Ghana',
  }],
},
{
  id: 2,
  name: 'abc Nig. Ltd',
  services: 'Mobile Development',
  phone_number: '0123-456-789',
  email: 'abc@gmail.com',
  address: '1, abc street, Maitama, Abuja',
  category: 'Mobile Technology',
  location: 'Abuja',
  image: 'url2',
  reviews: [{
    id: 1,
    name: 'Gift Ayo',
    email: 'giftayo@email.com',
    review: 'I love you company and services, just keep it up',
    country: 'Brazil',
  },
  {
    id: 2,
    name: 'Steven Peter',
    email: 'stevenpeter@gmail.com',
    review: 'Good Job',
    country: 'Soweto',
  }],
}];

export default business;
